// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<ExtraUtilities:decorativeBlock1:8>, [[<minecraft:gold_ingot>, <minecraft:enchanted_book>, <minecraft:gold_ingot>], [<minecraft:enchanted_book>, <minecraft:bookshelf>, <minecraft:enchanted_book>], [<minecraft:gold_ingot>, <minecraft:enchanted_book>, <minecraft:gold_ingot>]]);
recipes.removeShaped(<ExtraUtilities:angelRing>, [[<ExtraUtilities:etherealglass>, <fakeores:fd_rainbow_block>, <ExtraUtilities:etherealglass>], [<fakeores:fd_rainbow_block>, <HardcoreEnderExpansion:essence>, <fakeores:fd_rainbow_block>], [<ore:ingotUnstable>, <fakeores:fd_rainbow_block>, <ore:ingotUnstable>]]);
recipes.removeShaped(<ExtraUtilities:angelRing>, [[<ore:blockGlassColorless>, <ore:ingotGold>, <ore:blockGlassColorless>], [<ore:ingotGold>, <minecraft:nether_star>, <ore:ingotGold>], [<ore:ingotUnstable>, <ore:ingotGold>, <ore:ingotUnstable>]]);
recipes.removeShaped(<ExtraUtilities:angelRing:4>, [[<minecraft:gold_nugget>, <minecraft:gold_ingot>, <minecraft:gold_nugget>], [<minecraft:gold_ingot>, <minecraft:nether_star>, <minecraft:gold_ingot>], [<ExtraUtilities:unstableingot>, <minecraft:gold_ingot>, <ExtraUtilities:unstableingot>]]);
recipes.removeShaped(<ExtraUtilities:angelRing:3>, [[<minecraft:leather>, <ExtraUtilities:angelRing:3>], [<minecraft:leather>, null]]);
recipes.removeShaped(<ExtraUtilities:angelRing:3>, [[<minecraft:leather>, <minecraft:gold_ingot>, <minecraft:leather>], [<minecraft:gold_ingot>, <minecraft:nether_star>, <ore:ingotGold>], [<ore:ingotUnstable>, <ore:ingotGold>, <ore:ingotUnstable>]]);
recipes.removeShaped(<ExtraUtilities:angelRing:2>, [[<ore:dyePurple>, <ore:ingotGold>, <ore:dyePink>], [<ore:ingotGold>, <minecraft:nether_star>, <ore:ingotGold>], [<ore:ingotUnstable>, <ore:ingotGold>, <ore:ingotUnstable>]]);
recipes.removeShaped(<ExtraUtilities:angelRing:1>, [[<minecraft:feather>, <ore:ingotGold>, <minecraft:feather>], [<ore:ingotGold>, <minecraft:nether_star>, <ore:ingotGold>], [<ore:ingotUnstable>, <ore:ingotGold>, <ore:ingotUnstable>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<ExtraUtilities:unstableingot>, [<ore:blockUnstable>]);
recipes.addShapeless(<ExtraUtilities:angelRing:4>, [<minecraft:gold_nugget>, <ExtraUtilities:angelRing>, <minecraft:gold_nugget>]);
recipes.addShapeless(<ExtraUtilities:angelRing:3>, [<minecraft:leather>, <ExtraUtilities:angelRing>, <minecraft:leather>]);
recipes.addShapeless(<ExtraUtilities:angelRing:3>, [<minecraft:leather>, <ExtraUtilities:angelRing:3>, <minecraft:leather>]);
recipes.addShapeless(<ExtraUtilities:angelRing:2>, [<ore:dyePurple>, <ExtraUtilities:angelRing>, <ore:dyePink>]);
recipes.addShapeless(<ExtraUtilities:angelRing:1>, [<minecraft:feather>, <ExtraUtilities:angelRing>, <minecraft:feather>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<fakeores:fd_rainbow_block>, [[<dextersnether:item>, <dextersnether:item>, <dextersnether:item>], [<dextersnether:item>, <fakeores:fd_rainbow_ingot>, <dextersnether:item>], [<dextersnether:item>, <dextersnether:item>, <dextersnether:item>]]);
recipes.addShaped(<ExtraUtilities:decorativeBlock1:8>, [[<minecraft:golden_apple>, <minecraft:enchanted_book>, <minecraft:golden_apple>], [<minecraft:enchanted_book>, <minecraft:bookshelf>, <minecraft:enchanted_book>], [<minecraft:golden_apple>, <minecraft:enchanted_book>, <minecraft:golden_apple>]]);
recipes.addShaped(<HostileWorlds:curseAura>, [[<dextersnether:item>, <fakeores:fd_rainbow_ingot>, <dextersnether:item>], [<fakeores:fd_rainbow_ingot>, <minecraft:mossy_cobblestone>, <fakeores:fd_rainbow_ingot>], [<dextersnether:item>, <fakeores:fd_rainbow_ingot>, <dextersnether:item>]]);
recipes.addShaped(<HostileWorlds:invasionSource>, [[<dextersnether:item>, <fakeores:fd_strangeliquid_bucket>, <dextersnether:item>], [<fakeores:fd_strangeliquid_bucket>, <minecraft:mossy_cobblestone>, <fakeores:fd_strangeliquid_bucket>], [<dextersnether:item>, <fakeores:fd_strangeliquid_bucket>, <dextersnether:item>]]);
recipes.addShaped(<chocolateQuest:kingArmor>, [[<fakeores:fd_rainbow_ingot>, <minecraft:golden_helmet>, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>]]);
recipes.addShaped(<chocolateQuest:kingArmor>, [[<fakeores:fd_rainbow_ingot>, null, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>]]);
recipes.addShaped(<fakeores:fd_rainbow_ingot>, [[<ore:blockRedstone>, <ore:blockGold>, <ore:blockEmerald>], [<fakeores:fd_daren_block>, <fakeores:antiOreStone>, <minecraft:diamond_block>], [<fakeores:fd_blurk_block>, <ore:blockLapis>, <fakeores:fd_purlight_block>]]);
recipes.addShaped(<ExtraUtilities:angelRing>, [[<dextersnether:item>, <fakeores:fd_rainbow_block>, <dextersnether:item>], [<fakeores:fd_rainbow_block>, <HardcoreEnderExpansion:essence>, <fakeores:fd_rainbow_block>], [<ore:ingotUnstable>, <fakeores:fd_rainbow_block>, <ore:ingotUnstable>]]);
recipes.addShaped(<SC0_Wings:fastWings>, [[<dextersnether:avis_wing>, <minecraft:feather>, <dextersnether:avis_wing>], [<minecraft:feather>, null, <minecraft:feather>]]);
recipes.addShaped(<evilMinecraftFixes:Unlocker Anvil>, [[<HardcoreEnderExpansion:essence>, <ore:blockUnstable>, <HardcoreEnderExpansion:essence>], [<HardcoreEnderExpansion:essence>, <HardcoreEnderExpansion:essence>, <HardcoreEnderExpansion:essence>], [<HardcoreEnderExpansion:essence>, <minecraft:nether_star>, <HardcoreEnderExpansion:essence>]]);
recipes.addShaped(<evilMinecraftFixes:Unlocker Anvil>, [[<HardcoreEnderExpansion:essence>, <HardcoreEnderExpansion:essence>, <HardcoreEnderExpansion:essence>], [<HardcoreEnderExpansion:essence>, <minecraft:nether_star>, <HardcoreEnderExpansion:essence>], [<HardcoreEnderExpansion:essence>, <HardcoreEnderExpansion:essence>, <HardcoreEnderExpansion:essence>]]);
recipes.addShaped(<evilMinecraftFixes:Unlocker Anvil>, [[<ExtraUtilities:unstableingot>, <ExtraUtilities:decorativeBlock1:5>, <ExtraUtilities:unstableingot>], [<ExtraUtilities:unstableingot>, <minecraft:nether_star>, <ExtraUtilities:unstableingot>], [<ExtraUtilities:unstableingot>, <ExtraUtilities:unstableingot>, <ExtraUtilities:unstableingot>]]);
recipes.addShaped(<ExtraUtilities:angelRing>, [[<ExtraUtilities:etherealglass>, <fakeores:fd_rainbow_block>, <ExtraUtilities:etherealglass>], [<fakeores:fd_rainbow_block>, <HardcoreEnderExpansion:essence>, <fakeores:fd_rainbow_block>], [<ore:ingotUnstable>, <fakeores:fd_rainbow_block>, <ore:ingotUnstable>]]);
recipes.addShaped(<ExtraUtilities:lawSword>, [[<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <minecraft:nether_star>, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>]]);
recipes.addShaped(<ParticleMan:particleglove>, [[<evilMinecraftFixes:Golden Feathers>, <ore:blockRedstone>, <ironbackpacks:treatedLeather>], [<ore:blockRedstone>, <ore:blockGold>, <ore:blockGold>], [<ironbackpacks:treatedLeather>, <ore:blockGold>, <ore:blockDiamond>]]);

// ================================================================================
//#MARKER ADD SHAPED QED
mods.extraUtils.QED.addShapedRecipe(<ExtraUtilities:decorativeBlock1:1> * 8, [[null, <minecraft:obsidian>, null], [<minecraft:obsidian>, <minecraft:ender_pearl>, <minecraft:obsidian>], [null, <minecraft:obsidian>, null]]);
mods.extraUtils.QED.addShapedRecipe(<chocolateQuest:kingArmor>, [[<fakeores:fd_rainbow_ingot>, null, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>], [<fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>, <fakeores:fd_rainbow_ingot>]]);
